config/routes.rb
Rails.application.routes.draw do

  get 'rooms/research' => 'rooms#research'
  post 'rooms/research' => 'rooms#research'

  resources :rooms do
    delete 'leave', on: :member
    post 'join', on: :member
  end

  resources :user do
    delete 'leave', on: :member
  end

  resources :rooms

  get '/tweets/new', to: 'tweets#new', as: 'new_tweet'

  get '/tweets/new2', to: 'tweets#new2', as: 'new2_tweet'

  get '/tweets/new3', to: 'tweets#new3', as: 'new3_tweet'

  post 'tweets/:id/edit', to: 'tweets#edit', as: 'edit_tweet'


  devise_for :users

  

  resources :users, only: [:edit]

  resources :comments, only: [:create] 

  resource :tweets

  get 'tweets/:id' => 'tweets#show',as: 'tweet'
  get 'tweets/:tweet_id/agrees' => 'agrees#create'
  get 'tweets/:tweet_id/agrees/:id' => 'agrees#destroy'
  patch 'tweets/:id' => 'tweets#update'
  patch 'tweets/:id' => 'tweets#update2'

  
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :agrees, only: [:create, :destroy]
    resources :resolves, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  
  #root ':tweets#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root 'hello#index'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/tweet.rb
class Tweet < ApplicationRecord

    belongs_to :user
    belongs_to :room

    has_many :agrees, dependent: :destroy
    has_many :agreed_users, through: :agrees, source: :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :resolves, dependent: :destroy
    has_many :resolved_users, through: :resolves, source: :user
    has_many :comments, dependent: :destroy
    #validates :name, presence: true 
    #has_many :tweet_tag_relations, dependent: :destroy
    #has_many :tags, through: :tweet_tag_relations, dependent: :destroy
    
    scope :unresolved, -> { where(resolved: false) }

    
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

    before_action :authenticate_user!, only: [:new, :create]
    before_action :set_rooms, only: [:new]

    def index
        @tweets = Tweet.all
    end

    
    def new
        @user = current_user 
        @room = Room.new
        @room.users << current_user
        @rooms = Room.includes(:teacher)
              .where(id: current_user.user_rooms.pluck(:room_id))
              .order(Arel.sql("CASE WHEN day_of_week = '月' THEN 0 
                                WHEN day_of_week = '火' THEN 1 
                                WHEN day_of_week = '水' THEN 2 
                                WHEN day_of_week = '木' THEN 3 
                                WHEN day_of_week = '金' THEN 4 
                                ELSE 5 END"))
              .order(Arel.sql("CASE WHEN period = '1限' THEN 0 
                                WHEN period = '2限' THEN 1 
                                WHEN period = '3限' THEN 2 
                                WHEN period = '4限' THEN 3 
                                WHEN period = '5限' THEN 4 
                                WHEN period = '6限' THEN 5 
                                ELSE 6 END"))
        @rooms_all = Room.all
        @comment = Comment.new
        @comment = Comment.new

      
        if params[:id].present?
          @tweet = Tweet.find(params[:id])
          @comments = tweet.comments
          @unresolved_tweets = @user.tweets.where(resolved: false)
        else
          @tweet = current_user.tweets.new
          @comments = []  
          @tweets = Tweet.all
        end
    end
      

    def new2
      @user = current_user 
      @room = Room.new
      @room.users << current_user
      @rooms = Room.includes(:teacher).where(id: current_user.user_rooms.pluck(:room_id)).order(updated_at: :desc)
      @rooms_all = Room.all
      @comment = Comment.new
      @comment = Comment.new

    
      if params[:id].present?
        @tweet = Tweet.find(params[:id])
        @comments = tweet.comments
        @unresolved_tweets = @user.tweets.where(resolved: false)
      else
        @tweet = current_user.tweets.new
        @comments = []  
        @tweets = Tweet.all
      end
  end
      
  def new3
    @user = current_user 
    @room = Room.new
    @room.users << current_user
    @rooms = Room.includes(:teacher).where(id: current_user.user_rooms.pluck(:room_id)).order(updated_at: :desc)
    @rooms_all = Room.all
    @comment = Comment.new
    @comment = Comment.new

  
    if params[:id].present?
      @tweet = Tweet.find(params[:id])
      @comments = tweet.comments
      @unresolved_tweets = @user.tweets.where(resolved: false)
    else
      @tweet = current_user.tweets.new
      @comments = []  
      @tweets = Tweet.all
    end
end

    def create
        @room = Room.find_by(id: params[:room_id])
        @tweet = current_user.tweets.build(tweet_params)
        @tweet.room_id = params[:room_id]
        tweet = Tweet.new(tweet_params)
        tweet.user_id = current_user.id

        if tweet.save!
          redirect_to room_path(params[:tweet][:room_id]), notice: 'ツイートが作成されました。'
        else
          redirect_to room_path(params[:tweet][:room_id]), alert: 'ツイートの作成に失敗しました。'
        end

        if @tweet.save
           redirect_to room_path(@room.id)
        end
    end

    def show
        @tweet = Tweet.find(params[:id])
        @comments = @tweet.comments
        @comment = Comment.new
        @user = current_user 
        @tweets = Tweet.all
        @room = Room.new
        @room.users << current_user
        @rooms = Room.includes(:teacher)
        .where(id: current_user.user_rooms.pluck(:room_id))
        .order(Arel.sql("CASE WHEN day_of_week = '月' THEN 0 
                          WHEN day_of_week = '火' THEN 1 
                          WHEN day_of_week = '水' THEN 2 
                          WHEN day_of_week = '木' THEN 3 
                          WHEN day_of_week = '金' THEN 4 
                          ELSE 5 END"))
        .order(Arel.sql("CASE WHEN period = '1限' THEN 0 
                          WHEN period = '2限' THEN 1 
                          WHEN period = '3限' THEN 2 
                          WHEN period = '4限' THEN 3 
                          WHEN period = '5限' THEN 4 
                          WHEN period = '6限' THEN 5 
                          ELSE 6 END"))
        @rooms_all = Room.all
    end


    def edit
        @tweet = Tweet.find(params[:id])
        session[:previous_url] = request.referer
        @rooms = Room.includes(:teacher).where(id: current_user.user_rooms.pluck(:room_id)).order(updated_at: :desc)
        @user = current_user 
    end

    def destroy
        tweet = Tweet.find(params[:id])
        @room = tweet.room
        tweet.destroy
        redirect_to action: :new
    end

    def update
        tweet = Tweet.find(params[:id])
        @tweet = Tweet.find(params[:id])
        @room = tweet.room

        if tweet.update(tweet_params)
            redirect_to :action => "new", :id => tweet.id
          else
            redirect_to :action => "new"
          end
    end

    def update2
        tweet = Tweet.find(params[:id])
        @tweet = Tweet.find(params[:id])
        @room = tweet.room

        if tweet.update(tweet_params)
            redirect_to session[:previous_url]
        else
            redirect_to :action => "new"
        end
    end

  
     private
      def room_params
        params.require(:room).permit(:roomname, :teacher_id, :teacher, :year, :semester, :day_of_week, :period, user_ids: [])
      end

      def tweet_params
        params.require(:tweet).permit(:body, :room_id)
      end

      def set_rooms
        @rooms = Room.all
      end

    end

app/views/tweets/edit.html.erb
<header>
  <h1 style="margin-left: 40px;">質問攻メモ</h1>
    <div class="header-list">
      <ul>
        <% if user_signed_in? %>
        <%= button_to "ログアウト", destroy_user_session_path, method: :delete, style: " font-weight: 600; font-size: 17px; color: white; background-color: transparent; border: none; padding: 0; margin-right: 25px;" %>
        <% else %>
        <%= link_to "新規登録", new_user_registration_path, style: "margin-right: 25px; margin-left: -20px;" %>
        <%= link_to "ログイン", new_user_session_path, style: "margin-right: 25px;" %>
        <% end %>
      </ul>
    </div>
</header>


<div class="sidebar-wrapper" style="overflow-y: auto; max-height: calc(100vh - 20px);">
  <div class="sidebar">
        <% if current_user.id == @user.id %>
            <div style="display: flex; align-items: center; position: relative;">
                <i class="fa-solid fa-circle-user fa-2xl" style="color: #3da6d4; margin-left: 15px;"></i>
                <div style="margin-left: 9px; color: black; font-size: 25px; font-weight: 600; font-family: Arial;">
                  <%= @user.name %>
                </div>
                <%= link_to edit_user_registration_path do %>
                  <i class="fa-solid fa-gear" style="color: #04527F; position: absolute; left: 214px; top: 30px;"></i>
                <% end %>
            </div>
        <% end %>

          <button class="sidebar-button" style="margin-top: 10px; ">
            <div style="position: relative; ">
              <a href="/tweets/new" style="background-color: #BADDF0; color: black; padding: 14px 14px 14px 0px; display: inline-block; width: 230px; font-weight: 600; position: relative; z-index: 1; ">マイページ</a>
              <i class="fa-solid fa-house" style="color: #04527F; position: absolute; top: 16px; left: 20px; z-index: 2; font-size: 25px;"></i>
            </div>
          </button>
        
        <button class="sidebar-button" style="margin-top: -25px;">
            <div style="position: relative;">
              <a href="/rooms" style="color: black; padding: 14px 14px 14px 0px; display: inline-block; width: 230px; font-weight: 600;">ルーム一覧</a>
              <i class="fa-solid fa-users" style="color: #04527F; position: absolute; top: 17px; left: 20px; z-index: 2; font-size: 25px;"></i>
              <i class="fa-solid fa-caret-down" style="color: #04527F; position: absolute; top: 17px; left: 173px; z-index: 2; font-size: 20px;"></i>
              <%= link_to rooms_research_path do %>
              <i class="fa-fw a-solid fa-plus" style="color: #04527F; position: absolute; top: 5px; left: 194px; z-index: 2; font-size: 40px;"></i>
              <% end %>
            </div>
        </button>
          
          
        <ul>
          <% @rooms.each do |room| %>
            <li>
            <%= link_to room_path(room), style: "font-size: 15px; color: #04527F; padding: 14px 14px 14px 0px; display: inline-block; width: 180px; font-weight: 600; margin-left: 40px; " do %>
              <span style="color: black;">【<%= room.roomname %>】</span> _ <%= room.teacher&.teacher || '未設定' %> _ <%= room.day_of_week %><%= room.period %>
            <% end %>          
            </li>
          <% end %>
        </ul>
  </div>
</div>



<div class="content">
<%= form_for @tweet do |f| %>
    <%= f.text_field :body, :size => 140 %> 
    <%= button_to "編集" , action: "update", controller: "tweets" %>
  <% end %>
</div>

<div class="sidebar-divider"></div>
<div class="sidebar-divider2"></div>

<footer>
<p>Copyright © 2024 Manon _ Kanon Matsumae</p>
</footer>

<style>

* {
  margin: 0;
  padding: 0;
}

body {
  font-family: "Hiragino Kaku Gothic Pro", "ヒラギノ角ゴ Pro W3", "メイリオ",
    Meiryo, "MS Ｐゴシック", sans-serif;
}

header {
  background-color: #04527F;
  height: 80px;
  font-weight: bold;
  display: flex;
  justify-content: space-between;
  align-items: center;
  position: fixed; /* ヘッダーを固定位置に配置 */
  width: 100%; /* ビューポートの幅に合わせてヘッダーを広げる */
  top: 0; /* ヘッダーをビューポートの上端に配置 */
  z-index: 1000;
}

header + * {
  margin-top: 120px; /* ヘッダーの高さと同じだけの上部の余白を追加 */
}

header a {
  color: white; 
  text-decoration: none; 
}


header h1 {
  color: white;
  margin-left: 20px;
}

.header-list {
  display: flex;
  align-items: center;
}

header ul {
  display: flex;
}

header li {
  list-style: none;
  margin-right: 40px;
}

.logout-button {
  background-color: transparent
  color: #ffffff; /* ボタンのテキスト色 */
  border: none; /* ボーダーをなくす */
  padding: 10px 20px; /* ボタンの内側の余白 */
  text-decoration: none; /* テキストの下線をなくす */
  font-weight: bolder; 
}

.sidebar {
    position: fixed;
    top: 120px;
    left: 0;
    height: 100%;
    flex-direction: column;
    width: 245px; /* サイドバーの幅を設定 */
    background-color: #fff; /* サイドバーの背景色を設定 */
    padding: 0px; /* ボタンの内側の余白を設定 */
    overflow-y: auto;
}

.sidebar-button {
    display: block;
    width: 100%;
    padding: 10px 0;
    margin-bottom: 10px;
    text-align: center;
    border: none;
    background-color: #fff; /* ボタンの背景色 */
    font-size: 18px;
    text-decoration: none;
    cursor: pointer;
}


.sidebar-link {
  color: black; /* リンクの文字色を黒にする */
}

.content {
    margin-left: 340px; /* サイドバーの幅 + 余白分を設定 */
    overflow-y: auto;
}

.sidebar-divider {
    position: fixed;
    top: 110px; /* サイドバーの上に110px分下の方から描く */
    left: 245px; /* サイドバーの幅 */
    height: calc(100% - 110px); /* サイドバーの上から110px分下の高さ */
    width: 5px; /* 線の幅 */
    background-color: #04527F; /* 線の色 */
}

.sidebar-divider2 {
    position: fixed;
    top: 112px; /* サイドバーの上に110px分下の方から描く */
    left: 250px; /* サイドバーの幅 */
    height: calc(100% - 110px); /* サイドバーの上から110px分下の高さ */
    width: 10px; /* 線の幅 */
    background-color: #D8D6D6; /* 線の色 */
}

a {
    text-decoration: none; /* 下線をなくす */
}

footer {
  color: white;
  height: 20px;
  background-color: #000;
  bottom: 0;
  width: 100%;
  display: flex;
  align-items: center;
  position: fixed;
  justify-content: flex-end;
}

</style>

app/views/tweets/new.html.erb
<header>
  <h1 style="margin-left: 40px;">質問攻メモ</h1>
    <div class="header-list">
      <ul>
        <% if user_signed_in? %>
          <%= button_to "ログアウト", destroy_user_session_path, method: :delete, style: " font-weight: 600; font-size: 17px; color: white; background-color: transparent; border: none; padding: 0; margin-right: 25px;" %>
        <% else %>
        <%= link_to "新規登録", new_user_registration_path, style: "margin-right: 25px; margin-left: -20px;" %>
        <%= link_to "ログイン", new_user_session_path, style: "margin-right: 25px;" %>
        <% end %>
      </ul>
    </div>
</header>

<div class="sidebar-wrapper" style="overflow-y: auto; max-height: calc(100vh - 20px);">
  <div class="sidebar">
        <% if current_user.id == @user.id %>
            <div style="display: flex; align-items: center; position: relative;">
                <i class="fa-solid fa-circle-user fa-2xl" style="color: #3da6d4; margin-left: 15px;"></i>
                <div style="margin-left: 9px; color: black; font-size: 25px; font-weight: 600; font-family: Arial;">
                  <%= @user.name %>
                </div>
                <%= link_to edit_user_registration_path do %>
                  <i class="fa-solid fa-gear" style="color: #04527F; position: absolute; left: 214px; top: 30px;"></i>
                <% end %>
            </div>
        <% end %>

          <button class="sidebar-button" style="margin-top: 10px; ">
            <div style="position: relative; ">
              <a href="/tweets/new" style="background-color: #BADDF0; color: black; padding: 14px 14px 14px 0px; display: inline-block; width: 230px; font-weight: 600; position: relative; z-index: 1; ">マイページ</a>
              <i class="fa-solid fa-house" style="color: #04527F; position: absolute; top: 16px; left: 20px; z-index: 2; font-size: 25px;"></i>
            </div>
          </button>
        
        <button class="sidebar-button" style="margin-top: -25px;">
            <div style="position: relative;">
              <a href="/rooms" style="color: black; padding: 14px 14px 14px 0px; display: inline-block; width: 230px; font-weight: 600;">ルーム一覧</a>
              <i class="fa-solid fa-users" style="color: #04527F; position: absolute; top: 17px; left: 20px; z-index: 2; font-size: 25px;"></i>
              <i class="fa-solid fa-caret-down" style="color: #04527F; position: absolute; top: 17px; left: 173px; z-index: 2; font-size: 20px;"></i>
              <%= link_to rooms_research_path do %>
                <i class="fa-fw a-solid fa-plus" style="color: #04527F; position: absolute; top: 5px; left: 194px; z-index: 2; font-size: 40px;"></i>
              <% end %>
            </div>
        </button>
          
          
        <div class="room-item" style="margin-bottom: 150px; ">
          <ul>
            <% @rooms.each do |room| %>
                <li>
                  <%= link_to room_path(room), style: "font-size: 15px; color: #04527F; padding: 14px 14px 14px 0px; display: inline-block; width: 180px; font-weight: 600; margin-left: 30px; " do %>
                    <span style="color: black;">【<%= room.roomname %>】</span> _ <%= room.teacher&.teacher || '未設定' %> _ <%= room.day_of_week %><%= room.period %>
                  <% end %>          
                </li>
            <% end %>
          </ul>
        </div>
  </div>
</div>


<div class="content">
      <div style="margin-left: 30px; padding-top: 30px; font-size: 20px; ">
        <h3>あなたの総質問数：<%= @tweets.count %> questions</h3>
      </div>
      <div class="index" style="margin-top: 45px; margin-bottom: 42px;  ">
        <%= link_to "あなたの全ての質問", new_tweet_path, style: "color: #04527F; padding: 14px 74px; border: 3.5px solid #04527F; font-weight: 650; margin-left: 30px; " %>
        <%= link_to "　いいねした質問　", new2_tweet_path, style: "color: #D8D6D6; padding: 14px 74px; border: 3.5px solid #D8D6D6; font-weight: 650; margin-left: -6px; " %>
        <%= link_to "　 未解決の質問 　", new3_tweet_path, style: "color: #D8D6D6; padding: 14px 74px; border: 3.5px solid #D8D6D6; font-weight: 650; margin-left: -9px; " %>
      </div>
      <div class="tweets-container">
          <% if @tweets.present? %>
            <% @tweets.each do |t| %>
              <div class="tweet" style=" position: relative; background-color: <%= current_user.already_resolved?(t) ? 'white' : '#ECF6FD' %>;">
                <div class="icon" style=" position: absolute; top: 6px; left: 0; padding: 20px;">
                  <% if current_user == t.user %>
                    <i class="fa-solid fa-circle-user fa-2xl" style="color: #3da6d4; margin-left: 15px;"></i>
                  <% else %>
                    <i class="fa-solid fa-circle-user fa-2xl" style="color: #C4C3C3; margin-left: 15px;"></i>
                  <% end %>
                </div>
                <p style=" font-weight: 600; margin-left: 20px; padding: 30px; font-size: 18px; margin-top: 26px;"><%= t.body %></p>
                <div class="upper-buttons" style=" position: absolute; top: 8px; right: 0; padding: 12px; display: flex; ">
                  <% if user_signed_in? %>
                    <% if current_user.already_agreed?(t) %>
                          <%= button_to tweet_agree_path(id: t.id, tweet_id: t.id), method: :delete, class: "custom-button" do %>
                            <i class="fa-solid fa-heart fa-xl"></i>
                            <%= t.agrees.count %>
                          <% end %>
                      <% else %>
                          <%= button_to tweet_agrees_path(id: t.id, tweet_id: t.id), method: :post, class: "custom-button2" do %>
                            <i class="fa-solid fa-heart fa-xl"></i>
                            <%= t.agrees.count %>
                          <% end %>
                    <% end %>
                    <% if current_user.already_resolved?(t) %>
                          <%= button_to tweet_resolve_path(id: t.id, tweet_id: t.id), method: :delete, class: "custom-button" do %>
                            <i class="fa-regular fa-circle-check" style="font-size: 20px; vertical-align: middle;"></i>
                            <%= content_tag(:span, t.resolves.count, style: "vertical-align: middle;") %>
                          <% end %>
                      <% else %>
                          <%= button_to tweet_resolves_path(id: t.id, tweet_id: t.id), method: :post, class: "custom-button2" do %>
                            <i class="fa-regular fa-circle-check" style="font-size: 20px; vertical-align: middle;"></i>
                            <%= content_tag(:span, t.resolves.count, style: "vertical-align: middle;") %>
                          <% end %>
                    <% end %>
                    <%= button_to tweet_path(t.id), method: :get, class: "custom-button" do %>
                      <i class="fa-regular fa-comment fa-xl"></i>
                      <%= t.comments.count %>
                    <% end %>
                  <% end %>
                </div>
                <% if not current_user.already_resolved?(t) %>
                  <div class="unresolved-badge">
                    <p class="unresolved-text" style="font-size: 10px; font-weight: bolder; "></p>
                  </div>
                <% end %>
                <div class="down-buttons" style=" position: absolute; margin-top: -30px; right: 0; padding: 12px; display: flex; ">
                    <div class="roomname" style=" font-size: 17px; font-weight: bolder; margin-right: 6px; ">
                    <span><%= t.room.roomname %></span>
                    </div>
                    <%= button_to room_path(t.room), method: :get, class: "custom-button3" do %>
                      <i class="fa-solid fa-arrow-right-to-bracket fa-flip-horizontal" style="font-size: 20px;"></i>
                    <% end %>                    
                  <% if current_user == t.user %>
                    <%= button_to edit_tweet_path(t.id), method: :get, class: "custom-button3" do %>
                      <i class="fa-solid fa-pen-to-square" style="font-size: 20px;"></i>
                    <% end %>
                    <%= button_to tweet_path(t.id), method: :delete, class: "custom-button3" do %>
                      <i class="fa-solid fa-trash-can" style="font-size: 20px;"></i>
                    <% end %>
                  <% end %>
                  </div>
                <div class="time" style="color: #A6A6A6; margin-top: -28px; ">
                  <span style="color: #A6A6A6; font-size: 11.5px; display: block; margin-left:832px ">
                    <%= t.created_at.strftime("%m/%d") %>
                  </span>
                  <span style="color: #A6A6A6; font-size: 13px; display: block; margin-left:830px ">
                  <%= t.created_at.strftime("%H:%M") %>
                  </span>
                </div>
              </div> 
            <% end %>
          <% else %>
            <p>まだ質問はありません。</p>
          <% end %>
      </div>
</div>

<div class="sidebar-divider"></div>
<div class="sidebar-divider2"></div>

<footer>
  <p>Copyright © 2024 Manon _ Kanon Matsumae</p>
</footer>



<style>



    .tweet {
      border: 3px solid black; /* 枠線の色と太さ */
      border-radius: 13px;
      padding: 10px; /* ツイート内容と枠線の間の余白 */
      margin-bottom: 20px; /* ツイート間の間隔 */
      width: 800px; /* 幅を指定 */
      margin-left: 90px;
    }

    .custom-button {
      background-color: #FFFFFF;
      color: #04527F;
      border-radius: 15px; /* 楕円形に */
      height: 28px; 
      border: 2.6px solid #04527F; 
      width: 55px;
    }

    .custom-button2 {
      background-color: #FFFFFF;
      color: #BDBBBB;
      border-radius: 15px; /* 楕円形に */
      height: 28px; 
      border: 2.6px solid #BDBBBB; 
      width: 55px;
    }

    .custom-button3 {
      background-color: transparent;
      color: #04527F;
      height: 24px; 
      border: 2px solid transparent; 
      width: 24px;
    }

    
    .unresolved-text {
      margin: 0; /* テキストの余白を削除 */
    }

    

    .content {
      margin-left: 280px; /* サイドバーの幅 + 余白分を設定 */
      margin-bottom: 50px;
    }

    * {
      margin: 0;
      padding: 0;
    }

    body {
      font-family: "Hiragino Kaku Gothic Pro", "ヒラギノ角ゴ Pro W3", "メイリオ",
        Meiryo, "MS Ｐゴシック", sans-serif;
    }

    header {
      background-color: #04527F;
      height: 80px;
      font-weight: bold;
      display: flex;
      justify-content: space-between;
      align-items: center;
      position: fixed; /* ヘッダーを固定位置に配置 */
      width: 100%; /* ビューポートの幅に合わせてヘッダーを広げる */
      top: 0; /* ヘッダーをビューポートの上端に配置 */
      z-index: 1000;
    }

    header + * {
      margin-top: 120px; /* ヘッダーの高さと同じだけの上部の余白を追加 */
    }

    header a {
      color: white; 
      text-decoration: none; 
    }


    header h1 {
      color: white;
      margin-left: 20px;
    }

    .header-list {
      display: flex;
      align-items: center;
    }

    header ul {
      display: flex;
    }

    header li {
      list-style: none;
      margin-right: 40px;
    }

    .logout-button {
      background-color: transparent
      color: #ffffff; /* ボタンのテキスト色 */
      border: none; /* ボーダーをなくす */
      padding: 10px 20px; /* ボタンの内側の余白 */
      text-decoration: none; /* テキストの下線をなくす */
      font-weight: bolder; 
    }

    .sidebar {
        position: fixed;
        top: 120px;
        left: 0;
        height: 100%;
        flex-direction: column;
        width: 245px; /* サイドバーの幅を設定 */
        background-color: #fff; /* サイドバーの背景色を設定 */
        padding: 0px; /* ボタンの内側の余白を設定 */
        overflow-y: auto;
    }

    .sidebar-button {
        display: block;
        width: 100%;
        padding: 10px 0;
        margin-bottom: 10px;
        text-align: center;
        border: none;
        background-color: #fff; /* ボタンの背景色 */
        font-size: 18px;
        text-decoration: none;
        cursor: pointer;
    }


    .sidebar-link {
      color: black; /* リンクの文字色を黒にする */
    }

    .content {
        margin-left: 340px; /* サイドバーの幅 + 余白分を設定 */
        overflow-y: auto;
    }

    .sidebar-divider {
        position: fixed;
        top: 110px; /* サイドバーの上に110px分下の方から描く */
        left: 245px; /* サイドバーの幅 */
        height: calc(100% - 110px); /* サイドバーの上から110px分下の高さ */
        width: 5px; /* 線の幅 */
        background-color: #04527F; /* 線の色 */
    }

    .sidebar-divider2 {
        position: fixed;
        top: 112px; /* サイドバーの上に110px分下の方から描く */
        left: 250px; /* サイドバーの幅 */
        height: calc(100% - 110px); /* サイドバーの上から110px分下の高さ */
        width: 10px; /* 線の幅 */
        background-color: #D8D6D6; /* 線の色 */
    }

    a {
        text-decoration: none; /* 下線をなくす */
    }

    footer {
      color: white;
      height: 20px;
      background-color: #000;
      bottom: 0;
      width: 100%;
      display: flex;
      align-items: center;
      position: fixed;
      justify-content: flex-end;
    }

    
</style>