config/routes.rb
Rails.application.routes.draw do

  get 'rooms/research' => 'rooms#research'
  post 'rooms/research' => 'rooms#research'

  resources :rooms do
    delete 'leave', on: :member
    post 'join', on: :member
  end

  resources :user do
    delete 'leave', on: :member
  end

  resources :rooms

  get '/tweets/new', to: 'tweets#new', as: 'new_tweet'

  get '/tweets/new2', to: 'tweets#new2', as: 'new2_tweet'

  get '/tweets/new3', to: 'tweets#new3', as: 'new3_tweet'

  post 'tweets/:id/edit', to: 'tweets#edit', as: 'edit_tweet'


  devise_for :users

  

  resources :users, only: [:edit]

  resources :comments, only: [:create] 

  resource :tweets

  get 'tweets/:id' => 'tweets#show',as: 'tweet'
  get 'tweets/:tweet_id/agrees' => 'agrees#create'
  get 'tweets/:tweet_id/agrees/:id' => 'agrees#destroy'
  patch 'tweets/:id' => 'tweets#update'
  patch 'tweets/:id' => 'tweets#update2'

  
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :agrees, only: [:create, :destroy]
    resources :resolves, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  
  #root ':tweets#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root 'hello#index'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/room.rb
class Room < ApplicationRecord
        validates :roomname, presence: true, uniqueness: true
        
        belongs_to :teacher
        has_many :user_rooms
        has_many :users, through: :user_rooms
        has_many :tweets
        accepts_nested_attributes_for :user_rooms

    end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

    def new
        @room = Room.new
        @room.users << current_user
    end
    
    def create
        teacher_name = params[:room].delete(:teacher)
        teacher = Teacher.find_or_create_by(teacher: teacher_name)
        @room = Room.new(room_params)
        @room.teacher = teacher
        @room.users << current_user
        
        if @room.save
          redirect_to room_path(@room), notice: 'ルームを作成しました', method: :post
        else
          redirect_to :action => "new"
        end
    end


    
    def index
        @user = current_user
        @rooms = Room.includes(:teacher)
        .where(id: current_user.user_rooms.pluck(:room_id))
        .order(Arel.sql("CASE WHEN day_of_week = '月' THEN 0 
                          WHEN day_of_week = '火' THEN 1 
                          WHEN day_of_week = '水' THEN 2 
                          WHEN day_of_week = '木' THEN 3 
                          WHEN day_of_week = '金' THEN 4 
                          ELSE 5 END"))
        .order(Arel.sql("CASE WHEN period = '1限' THEN 0 
                          WHEN period = '2限' THEN 1 
                          WHEN period = '3限' THEN 2 
                          WHEN period = '4限' THEN 3 
                          WHEN period = '5限' THEN 4 
                          WHEN period = '6限' THEN 5 
                          ELSE 6 END"))
        @room = Room.new
        @room.users << current_user
        search = params[:search]
        year = params[:year]
        semester = params[:semester]
        day_of_week = params[:day_of_week]
        period = params[:period]
    end
    
    def show
        @user = current_user
        @comment = Comment.new
        @room = Room.find_by(id: params[:id])
        if @room.nil?
            @room = Room.create
            flash[:notice] = '新しいルームが作成されました。'
        else
            if !@room.users.include?(current_user)
                @room.users << current_user
            end
        end
    
        if params[:id].present?
            @tweet = Tweet.find_by(id: params[:id])
            if @tweet
                @comments = @tweet.comments
            else
                @tweet = current_user.tweets.new
                @comments = []
            end
        else
            @tweet = current_user.tweets.new
            @comments = []
        end
        
        @tweets = Tweet.where(room_id: @room.id).all

        @rooms = Room.includes(:teacher)
                .where(id: current_user.user_rooms.pluck(:room_id))
                .order(Arel.sql("CASE WHEN day_of_week = '月' THEN 0 
                                  WHEN day_of_week = '火' THEN 1 
                                  WHEN day_of_week = '水' THEN 2 
                                  WHEN day_of_week = '木' THEN 3 
                                  WHEN day_of_week = '金' THEN 4 
                                  ELSE 5 END"))
                .order(Arel.sql("CASE WHEN period = '1限' THEN 0 
                                  WHEN period = '2限' THEN 1 
                                  WHEN period = '3限' THEN 2 
                                  WHEN period = '4限' THEN 3 
                                  WHEN period = '5限' THEN 4 
                                  WHEN period = '6限' THEN 5 
                                  ELSE 6 END"))

    end
    

    def edit
        @tweet = Tweet.find(params[:id])
        session[:previous_url] = request.referer
        @user = current_user
    end

    def destroy
        @tweet = Tweet.find(params[:id])
        if @tweet.destroy
          redirect_to room_path(@tweet.room), notice: 'ツイートが削除されました。'
        else
          redirect_to room_path(@tweet.room), alert: 'ツイートの削除に失敗しました。'
        end
    end

    def update
        @tweet = Tweet.find(params[:id])
        if @tweet.update(tweet_params)
        redirect_to session[:previous_url]
        else
          render :edit
        end
    end

      def research
        @user = current_user
        @room = Room.new
        @room.users << current_user
        @rooms = Room.includes(:teacher).order(updated_at: :desc)
        search = params[:search]
        year = params[:year]
        semester = params[:semester]
        day_of_week = params[:day_of_week]
        period = params[:period]

          @rooms = @rooms.where("roomname LIKE ? OR teacher LIKE ?", "%#{search}%", "%#{search}%") if search != nil and search != "" and search != "選択しない" 
          @rooms = @rooms.where(year: year) if year != nil and year != "" and  year != "選択しない" 
          @rooms = @rooms.where(semester: semester) if semester != nil and semester != "" and  semester != "選択しない" 
          @rooms = @rooms.where(day_of_week: day_of_week) if day_of_week != nil and day_of_week != "" and  day_of_week != "選択しない" 
          @rooms = @rooms.where(period: period) if period != nil and period != "" and  period != "選択しない" 
      
          if @rooms.empty?
            flash.now[:alert] = "該当する講義が見つかりませんでした。新しいルームを作成して、質問しよう！"
          end
          Rails.logger.debug("検索クエリ: #{search}")
          Rails.logger.debug("検索結果: #{@rooms.inspect}")

          @rooms2 = Room.includes(:teacher)
          .where(id: current_user.user_rooms.pluck(:room_id))
          .order(Arel.sql("CASE WHEN day_of_week = '月' THEN 0 
                            WHEN day_of_week = '火' THEN 1 
                            WHEN day_of_week = '水' THEN 2 
                            WHEN day_of_week = '木' THEN 3 
                            WHEN day_of_week = '金' THEN 4 
                            ELSE 5 END"))
          .order(Arel.sql("CASE WHEN period = '1限' THEN 0 
                            WHEN period = '2限' THEN 1 
                            WHEN period = '3限' THEN 2 
                            WHEN period = '4限' THEN 3 
                            WHEN period = '5限' THEN 4 
                            WHEN period = '6限' THEN 5 
                            ELSE 6 END"))


      end
      

      def leave
        @room = Room.find(params[:id])
        current_user.user_rooms.find_by(room_id: @room.id).destroy
        redirect_to rooms_path, notice: 'ルームから退会しました'
      end


      def join
        @room = Room.find(params[:id])
        user_room = current_user.user_rooms.find_or_initialize_by(room_id: @room.id)
        user_room.update(active: true)
        redirect_to @room, notice: 'ルームに参加しました'
      end


    private
    def room_params
        params.require(:room).permit(:roomname, :teacher_id, :teacher, :year, :semester, :day_of_week, :period, user_ids: [])
    end
    
    
    def tweet_params
        params.require(:tweet).permit(:body)
    end
end

app/views/rooms/edit.html.erb
<header>
  <h1 style="margin-left: 40px;">質問攻メモ</h1>
    <div class="header-list">
      <ul>
        <% if user_signed_in? %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete , style: "margin-right: 25px;" %>
        <% else %>
        <%= link_to "新規登録", new_user_registration_path, style: "margin-right: 25px; margin-left: -20px;" %>
        <%= link_to "ログイン", new_user_session_path, style: "margin-right: 25px;" %>
        <% end %>
      </ul>
    </div>
</header>


<div class="sidebar-wrapper" style="overflow-y: auto; max-height: calc(100vh - 20px);">
  <div class="sidebar">
        <% if current_user.id == @user.id %>
            <div style="display: flex; align-items: center; position: relative;">
                <i class="fa-solid fa-circle-user fa-2xl" style="color: #3da6d4; margin-left: 15px;"></i>
                <div style="margin-left: 9px; color: black; font-size: 25px; font-weight: 600; font-family: Arial;">
                  <%= @user.name %>
                </div>
                <%= link_to edit_user_registration_path do %>
                  <i class="fa-solid fa-gear" style="color: #04527F; position: absolute; left: 214px; top: 30px;"></i>
                <% end %>
            </div>
        <% end %>

          <button class="sidebar-button" style="margin-top: 10px; ">
            <div style="position: relative; ">
              <a href="/tweets/new" style="background-color: #BADDF0; color: black; padding: 14px 14px 14px 0px; display: inline-block; width: 230px; font-weight: 600; position: relative; z-index: 1; ">マイページ</a>
              <i class="fa-solid fa-house" style="color: #04527F; position: absolute; top: 16px; left: 20px; z-index: 2; font-size: 25px;"></i>
            </div>
          </button>
        
        <button class="sidebar-button" style="margin-top: -25px;">
            <div style="position: relative;">
              <a href="/rooms" style="color: black; padding: 14px 14px 14px 0px; display: inline-block; width: 230px; font-weight: 600;">ルーム一覧</a>
              <i class="fa-solid fa-users" style="color: #04527F; position: absolute; top: 17px; left: 20px; z-index: 2; font-size: 25px;"></i>
              <i class="fa-solid fa-caret-down" style="color: #04527F; position: absolute; top: 17px; left: 173px; z-index: 2; font-size: 20px;"></i>
              <%= link_to rooms_research_path do %>
              <i class="fa-fw a-solid fa-plus" style="color: #04527F; position: absolute; top: 5px; left: 194px; z-index: 2; font-size: 40px;"></i>
              <% end %>
            </div>
        </button>
          
          
        <ul>
          <% @rooms.each do |room| %>
            <li>
            <%= link_to room_path(room), style: "font-size: 15px; color: #04527F; padding: 14px 14px 14px 0px; display: inline-block; width: 180px; font-weight: 600; margin-left: 40px; " do %>
              <span style="color: black;">【<%= room.roomname %>】</span> _ <%= room.teacher&.teacher || '未設定' %> _ <%= room.day_of_week %><%= room.period %>
            <% end %>          
            </li>
          <% end %>
        </ul>
  </div>
</div>


<%= form_for @tweet do |f| %>
    <div class="field">
      <%= f.text_field :body, :size => 140 %>
    </div>
    <%= button_to "編集" , action: "update2", controller: "tweets" %>
<% end %>

app/views/rooms/new.html.erb
<header>
  <h1 style="margin-left: 40px;">質問攻メモ</h1>
    <div class="header-list">
      <ul>
        <% if user_signed_in? %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete , style: "margin-right: 25px;" %>
        <% else %>
        <%= link_to "新規登録", new_user_registration_path, style: "margin-right: 25px; margin-left: -20px;" %>
        <%= link_to "ログイン", new_user_session_path, style: "margin-right: 25px;" %>
        <% end %>
      </ul>
    </div>
</header>


<div class="sidebar-wrapper" style="overflow-y: auto; max-height: calc(100vh - 20px);">
  <div class="sidebar">
        <% if current_user.id == @user.id %>
            <div style="display: flex; align-items: center; position: relative;">
                <i class="fa-solid fa-circle-user fa-2xl" style="color: #3da6d4; margin-left: 15px;"></i>
                <div style="margin-left: 9px; color: black; font-size: 25px; font-weight: 600; font-family: Arial;">
                  <%= @user.name %>
                </div>
                <%= link_to edit_user_registration_path do %>
                  <i class="fa-solid fa-gear" style="color: #04527F; position: absolute; left: 214px; top: 30px;"></i>
                <% end %>
            </div>
        <% end %>

          <button class="sidebar-button" style="margin-top: 10px; ">
            <div style="position: relative; ">
              <a href="/tweets/new" style="background-color: #BADDF0; color: black; padding: 14px 14px 14px 0px; display: inline-block; width: 230px; font-weight: 600; position: relative; z-index: 1; ">マイページ</a>
              <i class="fa-solid fa-house" style="color: #04527F; position: absolute; top: 16px; left: 20px; z-index: 2; font-size: 25px;"></i>
            </div>
          </button>
        
        <button class="sidebar-button" style="margin-top: -25px;">
            <div style="position: relative;">
              <a href="/rooms" style="color: black; padding: 14px 14px 14px 0px; display: inline-block; width: 230px; font-weight: 600;">ルーム一覧</a>
              <i class="fa-solid fa-users" style="color: #04527F; position: absolute; top: 17px; left: 20px; z-index: 2; font-size: 25px;"></i>
              <i class="fa-solid fa-caret-down" style="color: #04527F; position: absolute; top: 17px; left: 173px; z-index: 2; font-size: 20px;"></i>
              <%= link_to rooms_research_path do %>
              <i class="fa-fw a-solid fa-plus" style="color: #04527F; position: absolute; top: 5px; left: 194px; z-index: 2; font-size: 40px;"></i>
              <% end %>
            </div>
        </button>
          
          
        <ul>
          <% @rooms.each do |room| %>
            <li>
            <%= link_to room_path(room), style: "font-size: 15px; color: #04527F; padding: 14px 14px 14px 0px; display: inline-block; width: 180px; font-weight: 600; margin-left: 40px; " do %>
              <span style="color: black;">【<%= room.roomname %>】</span> _ <%= room.teacher&.teacher || '未設定' %> _ <%= room.day_of_week %><%= room.period %>
            <% end %>          
            </li>
          <% end %>
        </ul>
  </div>
</div>



<h2>新しいルームを作成</h2>
<%= form_for @room do |f| %>
  <div class="field">
    <%= f.label :講義名 %>
    <%= f.text_field :roomname %>
  </div>
  <div class="field">
    <%= f.label :teacher, "担当教員" %>
    <%= f.text_field :teacher %>
  </div>
  <div class="field">
    <%= f.label :year, "年度" %>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :semester, "学期" %>
    <%= f.select :semester, options_for_select([["前期", "前期"], ["後期", "後期"]]) %>
  </div>
  <div class="field">
    <%= f.label :day_of_week, "曜日" %>
    <%= f.select :day_of_week, options_for_select([["月", "月"], ["火", "火"], ["水", "水"], ["木", "木"], ["金", "金"]]) %>
  </div>
  <div class="field">
    <%= f.label :period, "時限" %>
    <%= f.select :period, options_for_select([["1限", "1限"], ["2限", "2限"], ["3限", "3限"], ["4限", "4限"], ["5限", "5限"], ["6限", "6限"], ["7限", "7限"]]) %>
  </div>
  <%= f.submit "このルームを作成" %>
<% end %>

app/views/rooms/research.html.erb
<header>
  <h1 style="margin-left: 40px;">質問攻メモ</h1>
    <div class="header-list">
      <ul>
        <% if user_signed_in? %>
        <%= button_to "ログアウト", destroy_user_session_path, method: :delete, style: " font-weight: 600; font-size: 17px; color: white; background-color: transparent; border: none; padding: 0; margin-right: 25px;" %>
        <% else %>
        <%= link_to "新規登録", new_user_registration_path, style: "margin-right: 25px; margin-left: -20px;" %>
        <%= link_to "ログイン", new_user_session_path, style: "margin-right: 25px;" %>
        <% end %>
      </ul>
    </div>
</header>


<div class="sidebar-wrapper" style="overflow-y: auto; max-height: calc(100vh - 20px);">
  <div class="sidebar">
        <% if current_user.id == @user.id %>
            <div style="display: flex; align-items: center; position: relative;">
                <i class="fa-solid fa-circle-user fa-2xl" style="color: #3da6d4; margin-left: 15px;"></i>
                <div style="margin-left: 9px; color: black; font-size: 25px; font-weight: 600; font-family: Arial;">
                  <%= @user.name %>
                </div>
                <%= link_to edit_user_registration_path do %>
                  <i class="fa-solid fa-gear" style="color: #04527F; position: absolute; left: 214px; top: 30px;"></i>
                <% end %>
            </div>
        <% end %>

          <button class="sidebar-button" style="margin-top: 10px; ">
            <div style="position: relative; ">
              <a href="/tweets/new" style="color: black; padding: 14px 14px 14px 0px; display: inline-block; width: 230px; font-weight: 600; position: relative; z-index: 1; ">マイページ</a>
              <i class="fa-solid fa-house" style="color: #04527F; position: absolute; top: 16px; left: 20px; z-index: 2; font-size: 25px;"></i>
            </div>
          </button>
        
        <button class="sidebar-button" style="margin-top: -25px;">
            <div style="position: relative;">
              <a href="/rooms" style="background-color: #BADDF0; color: black; padding: 14px 14px 14px 0px; display: inline-block; width: 230px; font-weight: 600;">ルーム一覧</a>
              <i class="fa-solid fa-users" style="color: #04527F; position: absolute; top: 17px; left: 20px; z-index: 2; font-size: 25px;"></i>
              <i class="fa-solid fa-caret-down" style="color: #04527F; position: absolute; top: 17px; left: 173px; z-index: 2; font-size: 20px;"></i>
              <%= link_to rooms_research_path do %>
              <i class="fa-fw a-solid fa-plus" style="color: #04527F; position: absolute; top: 5px; left: 194px; z-index: 2; font-size: 40px;"></i>
              <% end %>
            </div>
        </button>
          

        <div class="room-item" style="margin-bottom: 150px; ">
          <ul>
            <% @rooms2.each do |room| %>
                <li>
                <%= link_to room_path(room), style: "font-size: 15px; color: #04527F; padding: 14px 14px 14px 0px; display: inline-block; width: 180px; font-weight: 600; margin-left: 40px; " do %>
                  <span style="color: black;">【<%= room.roomname %>】</span> _ <%= room.teacher&.teacher || '未設定' %> _ <%= room.day_of_week %><%= room.period %>
                <% end %>          
                </li>
            <% end %>
          </ul>
        </div>
  </div>
</div>


<div class="content">
    <div class="research-form">
      <h1>ルームを探す</h1>
          <%= form_tag({controller:"rooms",action:"research"}, method: :get) do %>
            <div style="position: relative; padding: 20px; ">
              <i class="fa-solid fa-magnifying-glass" style="position: absolute; left: 39px; top: 50%; transform: translateY(-50%);"></i>
              <%= text_field_tag :search, nil, placeholder: "講義名 or 担当教員を入力", style: "padding: 8px;  width: 900px; font-size: 17px; text-indent: 35px; border: 2.5px solid #04527F;", class: "search-input" %>
            </div>
            <div style="display: flex; margin-left: 30px; ">
              <div class="field custom-border" style="margin-right: 10px;">
                <%= label_tag :year, "年度" %>
                <%= number_field_tag :year, params[:year], style: "margin-left: 6px; padding: 6px; border: 2px solid #04527F;" %>
              </div>
              <div class="field custom-border" style="margin-right: 10px;">
                <%= label_tag :semester, "学期" %>
                <%= select_tag :semester, options_for_select([["選択しない", "選択しない"], ["前期", "前期"], ["後期", "後期"]], params[:semester]), style: "margin-left: 6px; padding: 6px; border: 2px solid #04527F;" %>
              </div>
              <div class="field custom-border" style="margin-right: 10px;">
                <%= label_tag :day_of_week, "曜日" %>
                <%= select_tag :day_of_week, options_for_select([["選択しない", "選択しない"], ["月", "月"], ["火", "火"], ["水", "水"], ["木", "木"], ["金", "金"]], params[:day_of_week]), style: "margin-left: 6px; padding: 6px; border: 2px solid #04527F;" %>
              </div>
              <div class="field custom-border" style="margin-right: 10px;">
                <%= label_tag :period, "時限" %>
                <%= select_tag :period, options_for_select([["選択しない", "選択しない"], ["1限", "1限"], ["2限", "2限"], ["3限", "3限"], ["4限", "4限"], ["5限", "5限"], ["6限", "6限"], ["7限", "7限"]], params[:period]), style: "margin-left: 6px; padding: 6px; border: 2px solid #04527F;" %>
              </div> 
            </div>
            <%= submit_tag '検索する', style: "position: absolute; background-color: #04527F; color: white;  margin-left: 820px; border: 2px solid #04527F; padding: 5px; width: 90px;  margin-top:-42px; " %>
            <% end %>
    </div>

    <div class="room" style="margin-bottom: 50px; margin-top: 30px; margin-left: 30px; ">
    <% @rooms.each do |room| %>
      <p style="margin-top: 20px;"><%= room.roomname %></p>
      <% if room.teacher.present? %>
        担当教員: <%= room.teacher.teacher %>
      <% else %>
        担当教員: 未設定
      <% end %>
      <%= room.year %><span>年度</span>/<%= room.semester %>/<%= room.day_of_week %>曜/<%= room.period %>
      <% user_room = current_user.user_rooms.find_by(room_id: room.id) %>
      <% if user_room.present? %>
        <% if user_room.present? %>
          <%= link_to "このルームに参加する", room_path(room), method: :post %>
        <% else %>
          <%= link_to "このルームに再度参加する", join_room_path(room), method: :post %>
        <% end %>
      <% else %>
        <%= link_to "このルームに参加する", room_path(room), method: :post %>
      <% end %>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
        <h2>新しいルームを作成</h2>
    <%= form_for @room do |f| %>
      <div class="field">
        <%= f.label :講義名 %>
        <%= f.text_field :roomname %>
      </div>
      <div class="field">
        <%= f.label :teacher, "担当教員" %>
        <%= f.text_field :teacher %>
      </div>
      <div class="field">
        <%= f.label :year, "年度" %>
        <%= f.number_field :year %>
      </div>
      <div class="field">
        <%= f.label :semester, "学期" %>
        <%= f.select :semester, options_for_select([["前期", "前期"], ["後期", "後期"]]) %>
      </div>
      <div class="field">
        <%= f.label :day_of_week, "曜日" %>
        <%= f.select :day_of_week, options_for_select([["月", "月"], ["火", "火"], ["水", "水"], ["木", "木"], ["金", "金"]]) %>
      </div>
      <div class="field">
        <%= f.label :period, "時限" %>
        <%= f.select :period, options_for_select([["1限", "1限"], ["2限", "2限"], ["3限", "3限"], ["4限", "4限"], ["5限", "5限"], ["6限", "6限"], ["7限", "7限"]]) %>
      </div>
      <%= f.submit "このルームを作成" %>
    <% end %>
      </div>
    <% end %>
</div>

<div class="sidebar-divider"></div>
<div class="sidebar-divider2"></div>

<footer>
  <p>Copyright © 2024 Manon _ Kanon Matsumae</p>
</footer>


<style>

.search-input {
  color: black;
}
.search-input::placeholder {
  color: #999;
}

.search-input:focus::placeholder {
  color: transparent;
}

.custom-border {
  color: #04527F;
  padding: 8px;

}

* {
  margin: 0;
  padding: 0;
}

body {
  font-family: "Hiragino Kaku Gothic Pro", "ヒラギノ角ゴ Pro W3", "メイリオ",
    Meiryo, "MS Ｐゴシック", sans-serif;
}

header {
  background-color: #04527F;
  height: 80px;
  font-weight: bold;
  display: flex;
  justify-content: space-between;
  align-items: center;
  position: fixed; /* ヘッダーを固定位置に配置 */
  width: 100%; /* ビューポートの幅に合わせてヘッダーを広げる */
  top: 0; /* ヘッダーをビューポートの上端に配置 */
  z-index: 1000;
}

header + * {
  margin-top: 120px; /* ヘッダーの高さと同じだけの上部の余白を追加 */
}

header a {
  color: white; 
  text-decoration: none; 
}


header h1 {
  color: white;
  margin-left: 20px;
}

.header-list {
  display: flex;
  align-items: center;
}

header ul {
  display: flex;
}

header li {
  list-style: none;
  margin-right: 40px;
}

.logout-button {
  background-color: transparent
  color: #ffffff; /* ボタンのテキスト色 */
  border: none; /* ボーダーをなくす */
  padding: 10px 20px; /* ボタンの内側の余白 */
  text-decoration: none; /* テキストの下線をなくす */
  font-weight: bolder; 
}

.sidebar {
    position: fixed;
    top: 120px;
    left: 0;
    height: 100%;
    flex-direction: column;
    width: 245px; /* サイドバーの幅を設定 */
    background-color: #fff; /* サイドバーの背景色を設定 */
    padding: 0px; /* ボタンの内側の余白を設定 */
    overflow-y: auto;
}

.sidebar-button {
    display: block;
    width: 100%;
    padding: 10px 0;
    margin-bottom: 10px;
    text-align: center;
    border: none;
    background-color: #fff; /* ボタンの背景色 */
    font-size: 18px;
    text-decoration: none;
    cursor: pointer;
}


.sidebar-link {
  color: black; /* リンクの文字色を黒にする */
}

.content {
    margin-left: 340px; /* サイドバーの幅 + 余白分を設定 */
    overflow-y: auto;
}

.sidebar-divider {
    position: fixed;
    top: 110px; /* サイドバーの上に110px分下の方から描く */
    left: 245px; /* サイドバーの幅 */
    height: calc(100% - 110px); /* サイドバーの上から110px分下の高さ */
    width: 5px; /* 線の幅 */
    background-color: #04527F; /* 線の色 */
}

.sidebar-divider2 {
    position: fixed;
    top: 112px; /* サイドバーの上に110px分下の方から描く */
    left: 250px; /* サイドバーの幅 */
    height: calc(100% - 110px); /* サイドバーの上から110px分下の高さ */
    width: 10px; /* 線の幅 */
    background-color: #D8D6D6; /* 線の色 */
}

a {
    text-decoration: none; /* 下線をなくす */
}

footer {
  color: white;
  height: 20px;
  background-color: #000;
  bottom: 0;
  width: 100%;
  display: flex;
  align-items: center;
  position: fixed;
  justify-content: flex-end;
}


</style>